#!/usr/bin/env python3.9

print("addition and subtraction work like you expect")
print("2 + 2 is")
print(2 + 2)
print("10 - 4 is")
print(10 - 4)
print("so does multiplication and division")
print(3 * 9)
print(5 / 3)
print("floor division if you want it")
print(5 // 3)
print('modulo for remainders also like you expect')
print(5 % 3)
print('exponents with **')
print( 2 ** 3)
print('also with the pow method')
print( pow(2, 3) )
print('floating point math can mix with integers')
print( 1.1 + 3)
print( 4.0 + 3)
